### PR TITLE
Pr/stamp rename resources

### PR DESCRIPTION
**Pull request by Onset**

### CODE REVIEW

**Comment by enzy** [comment]
Tests are failing

**Comment by Onset** [comment]
Please don't merge yet.

**Comment by Onset** [comment]
@enzy Ready for merge or comments.

**Comment by enzy** [comment]
- [ ] replace `gulp-sequence` with `run-sequence`

**Comment by Onset** [comment]
@enzy `gulp-sequence` has been removed. Tests are passing. Changes are ready to be merged to `master`.

**Pull request merged**
