### PR TITLE
Pr/fix live reload

### PR DESCRIPTION
**Pull request by JirkaVebr**
I for one don't really like and use browserSync, and so I'm not fully certain as to whether this fix actually resolves the issues we've been facing. Therefore I would like to ask whoever ends up merging this to test it carefully.

Edit: The tests pass on my machine. I believe the CI is just having difficulties with what's already being addressed in #120.

### CODE REVIEW

**Comment by Cactucs** [comment]
fixes #118

**Comment by Onset** [comment]
Works for me. (`Windows`, `node v4.4.5`)

**Comment by Cactucs** [comment]
Here also (Linux, node v6.2.0)

**Comment by Onset** [comment]
fixes #118

**Pull request merged**
