### PR TITLE
Adding JS format support

### LINKED ISSUE #198: Allow config file to be plain .js
Motivation behind it:

> webpack has it; allows more complex things to be done; better extensibility

With this change it would be nice to:

- hooks can be JS functions also
- ... ?

So we're going to support various config options:

- yaml|yml
- json
- js

More wishes or ideas? 👂 

// cc @Cactucs @Onset

### PR DESCRIPTION
**Pull request by enzy**
More ideas and wishes?

---

Closes #198

### CODE REVIEW

**Comment by ViliamKopecky** [comment]
Idea: support async config :)

**Comment by enzy** [comment]
@ViliamKopecky Some background behind it please?

**Comment by Onset** [comment]
`mango.js`

```javacsript
module.exports = fetch('https://example.com/remoteConfig.json')
```

Not necessarily fetching the whole config; using it for a `data` part only would make sense to me too (https://github.com/manGoweb/mango-cli/blob/master/docs/config.md#data).

**Comment by ViliamKopecky** [comment]
Yes, or something with local filesystem. What other purpose would `.js` config have if it couldnt do async tasks.

**Comment by enzy** [comment]
You can require whatever you need in the JS config. Also async values can be awaited beforehand.

**Comment by Cactucs** [comment]
@enzy Is this going to work? I think that `await` works only in `async` method, which this is not. And top level await proposal is still in stage 2 at tc39...

**Comment by enzy** [comment]
My bad, now I get the case. See the draft in the latest commit...

**Comment by Cactucs** [comment]
This implementation means support only for node v7.6. Node 6 is in LTS maintenance mode (and will be until April 2019).

**Comment by enzy** [comment]
@Cactucs We already don't support Node 6 for some time. Look in the package.json:
```
 "engines": {
    "node": ">=8"
  },
```

**Pull request merged**
