### PR TITLE
Update .tern-project

### PR DESCRIPTION
**Pull request by Cactucs**
:warning: Generated by atom tern plugin

### CODE REVIEW

**Comment by enzy** [comment]
Are you sure it works with native Tern.js? (not included in the Atom)

**Comment by enzy** [comment]
`"ecmaVersion": 6` is a default value therefore not needed

**Comment by Cactucs** [comment]
Done.

**Comment by enzy** [comment]
Merged b4d7b56bb7ee2318bcbc93048cc1463ff78f145b

**Pull request closed without merging**
