### PR TITLE
Yaml config

### LINKED ISSUE #83: YAML config mango.yaml
better than json. Reading is easy, writing probably less easy. But there are probably libs for that.

### PR DESCRIPTION
**Pull request by Cactucs**
Fixes #83 
Docs updates

### CODE REVIEW

**Comment by ViliamKopecky** [comment]
Wow, that was quick :+1:

**Comment by enzy** [comment]
Well, it will do its work but I would be more pleased with a more refactored version...

**Comment by Cactucs** [comment]
:( :-1: I'll try... 

Separate JSON and YAML to two files and one calling them? Enough or more?

**Comment by enzy** [comment]
Focus on code simplicity and readability. Add some comments, avoid error catching when it's not necessary...

**Comment by Cactucs** [comment]
- simplicity :white_check_mark: (IMHO)
 - readability :white_check_mark: (IMHO)
 - comments (one - I don't know where to add them)  :-1: 
 - avoid error catching when it's not necessary :white_check_mark:  none added

...but sure something can be improved - I don't know what ;)

**Comment by enzy** [comment]
That's better! ;)

**Pull request merged**
