### PR TITLE
Watching images

### LINKED ISSUE #60: Watching images
When I have development mode and replace an image, the image is not replaced in the served environment.

### PR DESCRIPTION
**Pull request by Cactucs**
fixes #60

### CODE REVIEW

**Comment by Cactucs** [comment]
depends on #66

**Comment by enzy** [comment]
:+1:

**Comment by hexcross** [comment]
Cool!

**Comment by Cactucs** [comment]
Just a note: Images extension can be overwritten by mapping in config. The others not. (IMO a bug - my fault)

**Pull request merged**
