### PR TITLE
Svg sprites

### PR DESCRIPTION
**Pull request by Cactucs**
Currently breaks dev mode (unknown reason)

Needs to add compression (`sgvo`).

### CODE REVIEW

**Comment by Cactucs** [comment]
Will fix #61

**Comment by Cactucs** [comment]
And fail to generate more than one sprite (they are the same)

**Comment by Cactucs** [comment]
AFAIK works well, but makes the command exits, without waiting for others to do their job.

**Comment by Cactucs** [comment]
:tada: 
Should be without :bug:s  right now! 
Ready to merge! (But please review)

**Comment by enzy** [comment]
- [ ] Needs documentation
- [ ] What about tests? :P

**Comment by Cactucs** [comment]
I tested it once a it worked ;) 
I'll write some basic tests (on the same level as other tasks are tested)

**Comment by Cactucs** [comment]
Some tests included

**Pull request merged**
