### PR TITLE
WSL watch mode compatibility

### PR DESCRIPTION
**Pull request by enzy**
- use long polling when a WSL environment is detected
- @Onset please test and report back ;)

### CODE REVIEW

**Comment by enzy** [comment]
Related behavior can be achieved also with [is-docker](https://github.com/sindresorhus/is-docker/)

**Comment by Onset** [comment]
:top: :+1:

**Comment by Onset** [comment]
Hmm, on some projects it makes my PC very hot even when idle. 😄🔥  Almost all 16 cores utilized.

image

This PR has been running in dev mode (`mango dev`) during the red part, `mango-cli@3.2.0` during the green.

**Comment by enzy** [comment]
We may also try to combine it with limited watch scope (only src_dir) instead of working directory. But the CPU usage is the downside of a polling watch strategy.

**Comment by enzy** [comment]
A. Introduced `config.chokidar` for custom watcher options (via `mango.local.yaml`).
B. We still need to watch current working directory because of `dist_folder` and extra watched files from project config. 
C. There is no easy way how to detect type of watching of files (either inside VM or mounted from Windows host). The situation is even more complicated when we consider WSL 1 and WSL 2.

**Pull request closed without merging**
